sdk: iphone
author: Matěj Kašpar Jirásek
author_url: http://mkj.is
module: MKJIcons
version: 1.0
copyright: Copyright 2016 Matěj Kašpar Jirásek
readme: README.md
github_url: https://github.com/mkj-is/MKJIcons
